### ISSUE TITLE
continuously crashing

### ISSUE THREAD

**Issue by end3r-man** [ingageco/capacitor-music-controls-plugin#27]
log

```
 V  To native (Capacitor plugin): callbackId: 68199468, pluginId: CapacitorMusicControls, methodName: create
2024-09-22 12:56:36.523 14458-14458 Capacitor               demo.sala                            V  callback: 68199468, pluginId: CapacitorMusicControls, methodName: create, methodData: {"track":"Kurukku Siruthvalea","artist":"A R Rahman","album":"Mudhalvan","cover":"https:\/\/c.saavncdn.com\/711\/Mudhalvan-Tamil-1999-20190112180709-500x500.jpg","isPlaying":true,"hasPrev":false,"hasNext":false,"hasClose":true,"dismissable":true}
2024-09-22 12:56:36.542 14458-14527 CMCNotification         demo.sala                            I  updateNotification: infos: com.ingageco.capacitormusiccontrols.MusicControlsInfos@662c7f6
2024-09-22 12:56:36.543 14458-14458 MusicContr...Connection demo.sala                            I  onServiceConnected
2024-09-22 12:56:36.544 14458-14458 MusicContr...tionKiller demo.sala                            I  onStartCommand
2024-09-22 12:56:36.545 14458-14527 CapacitorCookies        demo.sala                            I  Getting cookies at: 'https://c.saavncdn.com/711/Mudhalvan-Tamil-1999-20190112180709-500x500.jpg'
2024-09-22 12:56:36.554 14458-14527 TrafficStats            demo.sala                            D  tagSocket(231) with statsTag=0xffffffff, statsUid=-1
2024-09-22 12:56:37.264 14458-14527 Capacitor               demo.sala                            E  Serious error executing plugin
                                                                                                    java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138)
                                                                                                    	at com.getcapacitor.Bridge.lambda$callPluginMethod$0(Bridge.java:821)
                                                                                                    	at com.getcapacitor.Bridge.$r8$lambda$ehFTi5f4HhVNFKTbCKAYDkpQYRA(Unknown Source:0)
                                                                                                    	at com.getcapacitor.Bridge$$ExternalSyntheticLambda3.run(Unknown Source:8)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
                                                                                                    	at com.ingageco.capacitormusiccontrols.MusicControlsNotification.createBuilder(MusicControlsNotification.java:203)
                                                                                                    	at com.ingageco.capacitormusiccontrols.MusicControlsNotification.updateNotification(MusicControlsNotification.java:79)
                                                                                                    	at com.ingageco.capacitormusiccontrols.CapacitorMusicControls.create(CapacitorMusicControls.java:83)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138) 
                                                                                                    	at com.getcapacitor.Bridge.lambda$callPluginMethod$0(Bridge.java:821) 
                                                                                                    	at com.getcapacitor.Bridge.$r8$lambda$ehFTi5f4HhVNFKTbCKAYDkpQYRA(Unknown Source:0) 
                                                                                                    	at com.getcapacitor.Bridge$$ExternalSyntheticLambda3.run(Unknown Source:8) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67) 
2024-09-22 12:56:37.265 14458-14527 AndroidRuntime          demo.sala                            E  FATAL EXCEPTION: CapacitorPlugins
                                                                                                    Process: demo.sala, PID: 14458
                                                                                                    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
                                                                                                    	at com.getcapacitor.Bridge.lambda$callPluginMethod$0(Bridge.java:830)
                                                                                                    	at com.getcapacitor.Bridge.$r8$lambda$ehFTi5f4HhVNFKTbCKAYDkpQYRA(Unknown Source:0)
                                                                                                    	at com.getcapacitor.Bridge$$ExternalSyntheticLambda3.run(Unknown Source:8)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138)
                                                                                                    	at com.getcapacitor.Bridge.lambda$callPluginMethod$0(Bridge.java:821)
                                                                                                    	at com.getcapacitor.Bridge.$r8$lambda$ehFTi5f4HhVNFKTbCKAYDkpQYRA(Unknown Source:0) 
                                                                                                    	at com.getcapacitor.Bridge$$ExternalSyntheticLambda3.run(Unknown Source:8) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67) 
                                                                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
                                                                                                    	at com.ingageco.capacitormusiccontrols.MusicControlsNotification.createBuilder(MusicControlsNotification.java:203)
                                                                                                    	at com.ingageco.capacitormusiccontrols.MusicControlsNotification.updateNotification(MusicControlsNotification.java:79)
                                                                                                    	at com.ingageco.capacitormusiccontrols.CapacitorMusicControls.create(CapacitorMusicControls.java:83)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138) 
                                                                                                    	at com.getcapacitor.Bridge.lambda$callPluginMethod$0(Bridge.java:821) 
                                                                                                    	at com.getcapacitor.Bridge.$r8$lambda$ehFTi5f4HhVNFKTbCKAYDkpQYRA(Unknown Source:0) 
                                                                                                    	at com.getcapacitor.Bridge$$ExternalSyntheticLambda3.run(Unknown Source:8) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67) 
2024-09-22 12:56:37.304 14458-14458 Capacitor/AppPlugin     demo.sala                            V  Notifying listeners for event pause
2024-09-22 12:56:37.304 14458-14458 Capacitor/AppPlugin     demo.sala                            D  No listeners found for event pause
2024-09-22 12:56:37.305 14458-14458 Capacitor               demo.sala                            D  App paused
2024-09-22 12:56:37.307 14458-14527 Process                 demo.sala                            I  Sending signal. PID: 14458 SIG: 9
```

**Comment by end3r-man** [comment]
code

```javascript
import { ref } from "vue";
import { CapacitorMusicControls } from "capacitor-music-controls-plugin";

export default function useCount() {

    const store = ref({
        isPlaying: false,
        audio: null,
        Artists: String,
        Title: String,
        Album: String,
        Image: String,
        Song: String
    })

    function setSong(params) {
        store.value.Image = params.image[2].url
        store.value.Album = params.album.name
        store.value.Title = params.name
        store.value.Artists = params.artists.all[0].name
        store.value.Song = params.downloadUrl[4].url

        HandelPlay()
    }

    function getSong(params) {

    }

    function HandelPlay() {

        if (store.value.isPlaying) {
            store.value.audio.pause()
            store.value.audio.src = ''
        }

        store.value.audio = new Audio()
        store.value.audio.src = store.value.Song

        CapacitorMusicControls.create({
            track: store.value.Title,
            artist: store.value.Artists,
            album: store.value.Album,
            cover: store.value.Image, 
            isPlaying: true,
            hasPrev: false, // show previous button, optional, default: true
            hasNext: false,
            hasClose: true,
            dismissable: true,
        })

        setTimeout(() => {
            store.value.audio.play()
            store.value.isPlaying = true
        }, 200);
    }


    return {
        store,
        setSong,
        getSong
    }
}
```

**Comment by ingageco** [comment]
@end3r-man this plugin is only tested in conjunction with the Cordova Media plugin and not with web audio.

**Comment by end3r-man** [comment]
which plugin should i use with??

**Comment by ingageco** [comment]
Cordova Media - it works with Capacitor perfectly fine: 

https://cordova.apache.org/docs/en/9.x/reference/cordova-plugin-media/
